name: Studio Build

on:
  pull_request:
    branches:
      - master
      - studio
    paths:
      - 'studio/**'
defaults:
  runs-on: ubuntu-latest
  strategy:
    matrix:
      node-version: [14.x]
      check-type: [build, lint, test, typecheck]
  working-directory: ./studio

jobs:
  check:
    name: ${{ matrix.check-type }}
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install deps
      run: npm ci
    - name: Run ${{ matrix.check-type }}
      run: npm run ${{ matrix.check-type }}
