name: Studio Build

on:
  pull_request:
    branches:
      - master
      - studio
    paths:
      - 'studio/**'
defaults:
  runs-on: ubuntu-latest
  strategy:
    matrix:
      node-version: [14.x]
  working-directory: ./studio

jobs:
  build:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install deps
      run: npm ci
    - name: Run build
      run: npm run build
      
  test:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install deps
      run: npm ci
    - name: Run test
      run: npm run test

  lint:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install deps
      run: npm ci
    - name: Run lint
      run: npm run lint

  typecheck:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install deps
      run: npm ci
    - name: Run typecheck
      run: npm run typecheck

